cart/urls.py
from django.urls import re_path as url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='details'),   #url to display the cart detail page
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='add'), #definition of url to add items to cart
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='remove'), # the url to remove product from cart

]
    #url(r'^$', views.cart_detail, name='cart_detail'),   #url to display the cart detail page
    #url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'), #definition of url to add items to cart

icanteen/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path as url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^\Z',         include('home.urls')),
    url(r'^admin/',     admin.site.urls),
    url(r'^polls/',     include('polls.urls')),
    url(r'^slideshow/', include('slideshow.urls')),
    url(r'^cart/',      include('cart.urls')),
    url(r'^orders/',    include('orders.urls')),
    url(r'^gallery/',   include('gallery.urls')),
    url(r'^payment/',   include('payments.urls')),
    url(r'^maps/',      include('maps.urls')),
    url(r'^users/',   include('users.urls')),
    url(r'^__debug__/',   include('debug_toolbar.urls')),
  ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import re_path as url
#from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'), #the url for order_create in the views.py file
    #path('admin/order/<int:order_id>pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    url(r'^pdf/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
    url(r'^pdf/(?P<order_id>\d+)/$', views.admin_order_pdf, name='admin_order_pdf'),
]
#url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),

cart/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)] #this will be used as a drop down for users to select quantity within the range on 1 to 26

class CartAddProductForm(forms.Form):  #this class will be used to add items to cart
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int) # here the field quantity is defined
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput) # update field is defined which will help in adding or updating of items

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST    # to post the form
from gallery.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from pprint import pprint
# Create your views here.
@require_POST # this is to ensure that only post request are allowed
def cart_add(request, product_id):    #a method to add items to the cart
    cart = Cart(request)  # create a new cart object passing it the request object
    product = get_object_or_404(Product, id=product_id)   # product is gotten from the database using the product id
    form = CartAddProductForm(request.POST)
    #id = request.POST.get("id")
    #quantity = request.POST.get("quantity")
    print(request)
    print(request.POST)
    if form.is_valid():   #if the form is validated products are added to cart and then updated
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')  # cart redirected to cart detail page


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):  #method to display the cart detail page
    cart = Cart(request)
    pprint(vars(cart))
    products = []
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
        products.append(item)
    context = { 'cart': cart }
    context['products'] = products
    return render(request, 'cart/detail.html', context)

#def cart_detail(request):
    #cart = Cart(request)
    #products = []
    #for item in cart:
        #item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
        #products.append(item)
    #context = { 'cart': cart }
    #context['products'] = products
    #return render(request, 'cart/detail.html', context)

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, CFA. {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #474E5D">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr style="background-color: #474E5D">
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.designation }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info" style="background-color: #474E5D">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>CFA. {{ item.price }}</td>
                            <td>CFA. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #474E5D">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>CFA. {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">

           <a href="{% url "orders:order_create" %}" class="btn btn-primary" style="background-color: #474E5D">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}