cart/urls.py
from django.urls import re_path as url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='details'),   #url to display the cart detail page
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='add'), #definition of url to add items to cart
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='remove'), # the url to remove product from cart

]
    #url(r'^$', views.cart_detail, name='cart_detail'),   #url to display the cart detail page
    #url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'), #definition of url to add items to cart

gallery/urls.py
from . import views
from django.urls import re_path as url

app_name = 'gallery'

urlpatterns = [
    # urls for the default gallery/
    url(r'^\Z',views.index,         name='index'),
    url(r'^wall/$',views.wall,      name='wall'),
    url(r'^search/$',views.search,  name='search'),
    url(r'^(?P<img_url>[\w/-]+_xl+[.]{1}[a-z]{3,4})/$',
        views.ExtraLargeThumbnailView.as_view(), 
        name='extra_large_thumb'
        ),
    url(r'^(?P<img_url>[\w/-]+_lg+[.]{1}[a-z]{3,4})/$',
        views.LargeThumbnailView.as_view(),
        name='large_thumb'
        ),
    url(r'^(?P<img_url>[\w/-]+_md+[.]{1}[a-z]{3,4})/$',
        views.MediumThumbnailView.as_view(),
        name='medium_thumb'
        ),
    url(r'^(?P<img_url>[\w/-]+_sm+[.]{1}[a-z]{3,4})/$',
        views.SmallThumbnailView.as_view(),
        name='small_thumb'
        ),
    url(r'^(?P<img_url>[\w/-]+[.]{1}[a-z]{3,4})/$',
        views.ThumbnailView.as_view(),
        name='thumbnail'
        ),
]

urlpatterns += [
        # urls for product
        url(r'^all/$',views.ProductListView.as_view(),name='all_products'),
        url(r'^(?P<category_slug>[-\w]+)/$',
            views.ProductListView.as_view(),
            name='category_detail'
            ),
        url(r'^product/largeView/$',
            views.ProductListLargeView.as_view(),
            name='large_view'
            ),
        url(r'^product/extraLargeView/$',
            views.ProductListExtraLargeView.as_view(),
            name='extra_large_view'
            ),
        url(r'^product/mediumView/$',
            views.ProductListMediumView.as_view(),
            name='medium_view'
            ),
        url(r'^product/smallView/$',
            views.ProductListSmallView.as_view(),
            name='small_view'
            ),
        url(r'^product/listView/$',
            views.ProductListListView.as_view(),
            name='list_view'
            ),
        url(r'^product/detailView/$',
            views.ProductListDetailView.as_view(),
            name='detail_view'
            ),
        url(r'^product/tileView/$',
            views.ProductListTileView.as_view(),
            name='tile_view'
            ),
        url(r'^product/contentView/$',
            views.ProductListContentView.as_view(),
            name='content_view'
            ),
        url(r'^product/create/$',
            views.ProductCreateView.as_view(),
            name='product_create'
            ),
        url(r'^product/detail/(?P<slug>\S+)/$',
            views.ProductDetailView.as_view(),
            name='product_detail'
            ),
        url(r'^product/update/(?P<slug>\S+)/$',
            views.ProductUpdateView.as_view(),
            name='product_update'
            ),
        #url(r'^product/$', views.ProductListView.as_view(), name='gallery_product_list'),
]

urlpatterns += [
    # urls for Category
    url(r'^category/$',
        views.CategoryListView.as_view(),
        name='gallery_category_list'
        ),
    url(r'^category/create/$',
        views.CategoryCreateView.as_view(),
        name='gallery_category_create'
        ),
    url(r'^category/update/(?P<slug>\S+)/$',
        views.CategoryUpdateView.as_view(),
        name='gallery_category_update'
        ),
    #url(r'^category/detail/(?P<category_slug>\S+)/$', views.ProductList, name='gallery_category_detail'),
]

icanteen/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path as url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^\Z',         include('home.urls')),
    url(r'^admin/',     admin.site.urls),
    url(r'^polls/',     include('polls.urls')),
    url(r'^slideshow/', include('slideshow.urls')),
    url(r'^cart/',      include('cart.urls')),
    url(r'^orders/',    include('orders.urls')),
    url(r'^gallery/',   include('gallery.urls')),
    url(r'^payment/',   include('payments.urls')),
    url(r'^maps/',      include('maps.urls')),
    url(r'^users/',   include('users.urls')),
    url(r'^__debug__/',   include('debug_toolbar.urls')),
  ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from __future__ import unicode_literals

from django.urls import reverse
from django.template.defaultfilters import slugify
from django.db import models
from decimal import Decimal
from .utils import unique_slug_factory

# Create your models here.

class Category(models.Model):
    # Fields
    # the id field is created by default as a surrogate key
    name = models.CharField(max_length=1024, null=False, unique=True, db_index=True)
    slug = models.SlugField(null=True, db_index=True, unique=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    views = models.IntegerField(default=0)
    image = models.ImageField(upload_to= 'category/', max_length=1024,
        default = 'no-img.jpg')
    class Meta:
        ordering = ('-created', 'name')
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    @property
    def title(self):
        return self.name

    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    def save(self, *args, **kwargs):
        # Uncomment if you don't want the slug to change every time the name changes
        #if self.id is None:
            #self.slug = slugify(self.name)
        # Creates a unique slug
        self.slug = slugify(unique_slug_factory(self))
        # call the mother class method to save the category
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('gallery:category_detail', args=(self.slug,))

    def get_update_url(self):
        return reverse('gallery:category_update', args=(self.slug,))

    def __unicode__(self):
        return u'%s' % self.slug

    def __str__(self):
        return self.name

class Product(models.Model):
    # Fields
    designation = models.CharField(max_length=1024, null=False, db_index=True, unique=True)
    slug = models.SlugField(null=True, db_index=True, unique=True)
    description = models.TextField(blank=False, null=False)
    packaging = models.CharField(max_length=4096, null=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    views = models.IntegerField(default=0)
    image = models.ImageField(upload_to= 'product/', max_length=1024,
        default = 'no-img.jpg')
    category = models.ForeignKey(Category, related_name= 'product', on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created', 'designation')
        index_together = (('id', 'slug'),)

    @property
    def title(self):
        return self.designation

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    def save(self, *args, **kwargs):
        # Uncomment if you don't want the slug to change every time the name changes
        #if self.id is None:
            #self.slug = slugify(self.name)
        self.slug = slugify(unique_slug_factory(self))
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('gallery:product_detail', args=(self.slug,))

    def get_update_url(self):
        return reverse('gallery:product_update', args=(self.slug,))

    def __unicode__(self):
        return u'%s' % self.slug

    def __str__(self):
        return self.designation


class OrderItem(models.Model):
    # Fields
    quantity = models.IntegerField(default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    #customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product  = models.ForeignKey(Product, on_delete=models.CASCADE)
    #order    = models.ForeignKey(Order, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created',)

    @property
    def product_name(self):
        return self.product

    #@property
    #def customer_name(self):
            #return self.customer
    @property
    #def order_code(self):
            #return self.order

    def get_absolute_url(self):
        return reverse('gallery:order_item_detail', args=(self.slug,))

    def get_update_url(self):
        return reverse('gallery:order_item_update', args=(self.slug,))

    def __unicode__(self):
        return u'%s' % self.slug

    def __str__(self):
        return self.designation

gallery/forms.py
from django import forms
from .models import Product, Category


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['designation', 'slug', 'description', 'packaging', 'price', 'image', 'category']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'slug', 'image', 'views']

gallery/templates/gallery/CartBase.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}I-Canteen{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% include 'gallery/navbar.html' %}

<div class="container">
    <div class="row" style="margin-top: 6%">
         <button class="btn btn-info pull-right">
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                    My Shopping Order:
                    <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                        {{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
                    </a>
                    {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
         </button>
    </div>
</div>
{% block content %}


{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

gallery/templates/gallery/category_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<style>
    @media (min-width: 992px) {
        body {
        padding-top: 56px;
        }
    }
</style>

<!---------------------------------- Wall ----------------------------------->
<div class="container">
    <h1 class="my-4 text-center text-lg-left">Categories</h1>
    <div class="row text-center text-lg-left">
        {% for object in object_list %}
        <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
            <a href="{{object.get_absolute_url}}" class="d-block mb-4 h-100">
                <img class="img-thumbnail"
                    src = "{% static 'gallery/img/loading.gif' %}"
                    alt="{{ object.name }}"
                    data-url = "{{object.image_url}}"/>
            </a>
        </div>
        {% endfor %}
    </div>
</div>


<script>
    $(".img-thumbnail").each(
        function(){
            img_number = $(".img-thumbnail").index(this);
            console.log("loading image number "+ img_number);
            var p = $(this).parent();
            console.log($(this).attr('data-url').split('/',4)[3]);
            $.ajax({
                type: "GET",
                url: $(this).attr('data-url').split('/',4)[3],
                contentType:'application/x-www-form-urlencoded; charset=UTF-8',
                dataType: "html",
                success: function(response) {
                    console.log(response)
                    p.html(response);
                },
                error: function (xhr, status) {
                  p.html("Error: " + xhr.status + ": " + xhr.statusText);
                }
            });
        }
    );
</script>
{% endblock %}

gallery/templates/gallery/dropdown.html
<style>
        .price{
        color: #474E5D;
    }
     .name{
        color: #474E5D;
    }

   .dropdown{
         float: right;
        position: relative;
         display: inline-block;
         margin: 10px;
     }

</style>

   <!---------------------------------- dropdown-------------------------------------->
 <div class="container">
  <div class="row">
 <!---------------------------------- view ----------------------------------->
 <div class="col-sm-6">
  <div class="view">
    <div class="dropdown">
       <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" style = "background-color:#474E5D">View Type
        <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><a class="glyphicon glyphicon-stop" href={% url 'gallery:extra_large_view' %}> ExtraLarge </a></li>
                <li><a class="glyphicon glyphicon-unchecked" href={% url 'gallery:large_view' %}> Large </a></li>
                <li><a class="glyphicon glyphicon-th-large" href={% url 'gallery:medium_view' %}> Medium  </a></li>
                <li><a class="glyphicon glyphicon-th" href={% url 'gallery:small_view' %}> Small</a></li>
                <li><a class="glyphicon glyphicon-th-list" href={% url 'gallery:list_view' %}> List</a></li>
                <li><a class="glyphicon glyphicon-align-justify" href={% url 'gallery:detail_view' %}> Details</a></li>
                <li><a class=" glyphicon glyphicon-list-alt" href={% url 'gallery:small_view' %}> Tiles</a></li>
                <li><a class=" glyphicon glyphicon-list-alt" href={% url 'gallery:small_view' %}> Content</a></li>
              </ul>
    </div>
</div>

     <!---------------------------------- category----------------------------------->

</div>
</div>
</div>

gallery/templates/gallery/extra_large_thumbnail.html
<img class="img-thumbnail"
        src = "{{ media_url }}{{ img_thumb_url }}"
        alt="{{ media_url }}{{ img_thumb_url }}"
        media_url="{{ media_url }}"
        img_thumb_url="{{ img_thumb_url }}"
        img_url ="{{img_url}}"
        url_raw_0="{{url_raw_0}}"
        url_raw_1="{{url_raw_1}}"
        own_img_url="{{own_img_url}}"/>

gallery/templates/gallery/product_extralarge_list.html
{% extends "base.html" %}
{% block content %}
{% include 'gallery/search.html' %}
{% include 'gallery/dropdown.html' %}
{% load static %}
<style>
    @media (min-width: 992px) {
        body {
        padding-top: 56px;
        }
    }

        .price{
        color: #474E5D;
    }
     .name{
        color: #474E5D;
    }

    .list{
        float: right;
        position: relative;
         display: inline-block;
    }

       #sidebar{
        margin-top : 70px;

    }

    .paint{
       background-color :#F3F3F3;
    }
    .paintt{
       height: 100%;
    }

    .list-group-item{

        padding :5px;
        background-color :#F3F3F3
    }
    .list-group a{
      text-decoration: none;
    }

     li:hover{
        background-color :#A9A9A9
    }


</style>

<!---------------------------------- Wall ----------------------------------->

   <div class = "paintt">
   <div class="col-sm-2 sidebar-offcanvas" id="sidebar">
          <div class="list-group">
              <div class="form-group">
               <ul class="list-group">
                <Li class ="list-group-item active" style = "background-color:#474E5D">Categories</li>
                <Li class ="list-group-item" class="selected"><a href="{% url 'gallery:product_list' %}" style = "color:#474E5D">All</a></li>
                    {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected" {% endif %} class="list-group-item">
                   <a href="{{ c.get_absolute_url }}" style = "color:#474E5D" >{{ c.name }}</a></li>
                    {% endfor %}
            </ul>
            </div>
          </div>
        </div><!--/.sidebar-offcanvas-->
        </div>

<div class="container">
    <div class = "row">
    <div class = "col-sm-10">
    <div class = "list">
    <h1 class="my-4 text-center text-lg-left">{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    <h1 class="my-4 text-center text-lg-left">{% if query %}{{ query }}{% endif %}</h1>
    <div class ="paint">
    <div class="row text-center text-lg-left">
        {% for object in object_list %}
        <div class="col-lg-5 col-md-10 col-sm-10 col-xs-12" style="margin-top: 30px; margin-left: 50px;">
            <a href="{{object.get_absolute_url}}" class="d-block mb-4 h-100">
                <img class="img-thumbnail"
                    src = "{% static 'gallery/img/loading.gif' %}"
                    alt="{{ object.name }}"
                    data-url = "{{object.image_url}}"/>
            </a>
            <div>
                <h5 class = "name"><b>{{ object.designation }}</b></h5>
                <h5 class = "price"><b>Price:</b> {{ object.price}}CFA</h5>
                <h6 class = "price"><b>Description:</b>  {{ object.description|truncatewords:5}}</h6>
                 <div class="btn-group btn-groupe_2">
                   <button type="button" class="btn btn-primary" style = "background-color:#474E5D">Add to Cart
                    <span class="glyphicon glyphicon-shopping-cart"></span>
                   </button>
                </div>
              </div>
        </div>
        {% endfor %}
        </div>
    </div>
    </div>
</div>
</div>
{% include 'gallery/pagination.html' %}
</div>

<script>
       $(".img-thumbnail").each(
        function(){
            img_number = $(".img-thumbnail").index(this);
            console.log("loading image number "+ img_number);
            var p = $(this).parent();
            var dat_url = $(this).attr('data-url').split('/',4)[3];
            var url_split = dat_url.split('.');
            var url = url_split[0] + '_xl.' + url_split[1];

            //var url1_split = url.split('/',4)[3]);

            console.log('Data Url With the split = '+ dat_url);
            console.log('Data Url With the split = '+$(this).attr('data-url').split('.')[1]);
            console.log('Data Url With the split = '+ url);
            console.log('Data Url  = '+ dat_url);

            console.log('Data Url Without the split = '+$(this).attr('data-url'));
            //console.log('Data Url Without the split = '+ url1_split);

            $.ajax({
                type: "GET",
                url: url,
                contentType:'application/x-www-form-urlencoded; charset=UTF-8',
                dataType: "html",
                success: function(response) {
                    console.log(response)
                    p.html(response);
                },
                error: function (xhr, status) {
                  p.html("Error: " + xhr.status + ": " + xhr.statusText);
                }
            });
        }
    );

</script>
{% endblock %}

gallery/templates/gallery/product_list_detail.html
{% extends "base.html" %}
{% block content %}
{% include 'gallery/search.html' %}
{% include 'gallery/dropdown.html' %}
{% load static %}
<style>
    @media (min-width: 992px) {
        body {
        padding-top: 56px;
        }
    }

        .price{
        color: #474E5D;
    }
     .name{
        color: #474E5D;
    }

    .list{
        float: right;
        position: relative;
         display: inline-block;
    }

       #sidebar{
        margin-top : 70px;

    }

    .paint{
       background-color :#F3F3F3;
       margin-left: 80px;
       padding: 50px;
    }
    .paintt{
       height: 100%;
    }

    .list-group-item{

        padding :5px;
        background-color :#F3F3F3
    }
    .list-group a{
      text-decoration: none;
    }

     li:hover{
        background-color :#A9A9A9
    }

     img {
        float: left;
        padding: 10px;
}

</style>

<!---------------------------------- Wall ----------------------------------->

   <div class = "paintt">
   <div class="col-sm-2 sidebar-offcanvas" id="sidebar">
          <div class="list-group">
              <div class="form-group">
               <ul class="list-group">
                <Li class ="list-group-item active" style = "background-color:#474E5D">Categories</li>
                <Li class ="list-group-item" class="selected"><a href="{% url 'gallery:product_list' %}" style = "color:#474E5D">All</a></li>
                    {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected" {% endif %} class="list-group-item">
                   <a href="{{ c.get_absolute_url }}" style = "color:#474E5D" >{{ c.name }}</a></li>
                    {% endfor %}
            </ul>
            </div>
          </div>
        </div><!--/.sidebar-offcanvas-->
        </div>

<div class="container">
    <div class = "row">
    <div class = "col-sm-10">
    <div class = "list">
    <h1 class="my-4 text-center text-lg-left">{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    <h1 class="my-4 text-center text-lg-left">{% if query %}{{ query }}{% endif %}</h1>
    <div class ="paint">
    <div class="row text-center text-lg-left">
        {% for object in object_list %}
        <div class="col-lg-8 col-md-10 col-sm-10 col-xs-12" style="margin-left: 80px;>
            <a href="{{object.get_absolute_url}}" class="d-block mb-4 h-100"><hr style = "color: black;">
                <img src = "{{object.image_url}}" style="width:220px;height:220px; "/>
            </a>
            <div>
                <h5 class = "name" style = "margin-top: 70px;"><b>{{ object.designation }}</b></h5>
                <h5 class = "price"><b>Price:</b> {{ object.price}}CFA</h5>
                <h6 class = "price"><b>Description:</b>  {{ object.description|truncatewords:5}}</h6>
                <h6 class = "price"><b>Packaging:</b>  {{ object.packaging}}</h6>
                 <div class="btn-group btn-groupe_2">
                   <button type="button" class="btn btn-primary" style = "background-color:#474E5D">Add to Cart
                    <span class="glyphicon glyphicon-shopping-cart"></span>
                   </button>
                </div>
              </div>
        </div>
        {% endfor %}
        </div>
    </div>
    </div>
</div>
</div>
{% include 'gallery/pagination.html' %}
</div>

<script>
       $(".img-thumbnail").each(
        function(){
            img_number = $(".img-thumbnail").index(this);
            console.log("loading image number "+ img_number);
            var p = $(this).parent();
            var dat_url = $(this).attr('data-url').split('/',4)[3];
            var url_split = dat_url.split('.');
            var url = url_split[0] + '_extralargethumb.' + url_split[1];

            //var url1_split = url.split('/',4)[3]);

            console.log('Data Url With the split = '+ dat_url);
            console.log('Data Url With the split = '+$(this).attr('data-url').split('.')[1]);
            console.log('Data Url With the split = '+ url);
            console.log('Data Url  = '+ dat_url);

            console.log('Data Url Without the split = '+$(this).attr('data-url'));
            //console.log('Data Url Without the split = '+ url1_split);

            $.ajax({
                type: "GET",
                url: url,
                contentType:'application/x-www-form-urlencoded; charset=UTF-8',
                dataType: "html",
                success: function(response) {
                    console.log(response)
                    p.html(response);
                },
                error: function (xhr, status) {
                  p.html("Error: " + xhr.status + ": " + xhr.statusText);
                }
            });
        }
    );

</script>
{% endblock %}

gallery/templates/gallery/product_medium_list.html
{% extends "base.html" %}
{% block content %}
{% include 'gallery/search.html' %}
{% include 'gallery/dropdown.html' %}
{% load static %}
<style>
    @media (min-width: 992px) {
        body {
        padding-top: 56px;
        }
    }

        .price{
        color: #474E5D;
    }
     .name{
        color: #474E5D;
    }

    .list{
        float: right;
        position: relative;
         display: inline-block;
    }

       #sidebar{
        margin-top : 70px;

    }

    .paint{
       background-color :#F3F3F3;
    }
    .paintt{
       height: 100%;
    }

    .list-group-item{

        padding :5px;
        background-color :#F3F3F3
    }
    .list-group a{
      text-decoration: none;
    }

     li:hover{
        background-color :#A9A9A9
    }


</style>

<!---------------------------------- Wall ----------------------------------->

   <div class = "paintt">
   <div class="col-sm-2 sidebar-offcanvas" id="sidebar">
          <div class="list-group">
              <div class="form-group">
               <ul class="list-group">
                <Li class ="list-group-item active" style = "background-color:#474E5D">Categories</li>
                <Li class ="list-group-item" class="selected"><a href="{% url 'gallery:product_list' %}" style = "color:#474E5D">All</a></li>
                    {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected" {% endif %} class="list-group-item">
                   <a href="{{ c.get_absolute_url }}" style = "color:#474E5D" >{{ c.name }}</a></li>
                    {% endfor %}
            </ul>
            </div>
          </div>
        </div><!--/.sidebar-offcanvas-->
        </div>

<div class="container">
    <div class = "row">
    <div class = "col-sm-10">
    <div class = "list">
    <h1 class="my-4 text-center text-lg-left">{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    <h1 class="my-4 text-center text-lg-left">{% if query %}{{ query }}{% endif %}</h1>
    <div class ="paint">
    <div class="row text-center text-lg-left">
        {% for object in object_list %}
        <div class="col-lg-3 col-md-10 col-sm-10 col-xs-12" style="margin-top: 30px; margin-left: 50px;">
            <a href="{{object.get_absolute_url}}" class="d-block mb-4 h-100">
                <img class="img-thumbnail"
                    src = "{% static 'gallery/img/loading.gif' %}"
                    alt="{{ object.name }}"
                    data-url = "{{object.image_url}}"/>
            </a>
            <div>
                <h5 class = "name"><b>{{ object.designation }}</b></h5>
                <h5 class = "price"><b>Price:</b> {{ object.price}}CFA</h5>
                <h6 class = "price"><b>Description:</b>  {{ object.description|truncatewords:5}}</h6>
                 <div class="btn-group btn-groupe_2">
                   <button type="button" class="btn btn-primary" style = "background-color:#474E5D">Add to Cart
                    <span class="glyphicon glyphicon-shopping-cart"></span>
                   </button>
                </div>
              </div>
        </div>
        {% endfor %}
        </div>
    </div>
    </div>
</div>
</div>
{% include 'gallery/pagination.html' %}
</div>

<script>
       $(".img-thumbnail").each(
        function(){
            img_number = $(".img-thumbnail").index(this);
            console.log("loading image number "+ img_number);
            var p = $(this).parent();
            var dat_url = $(this).attr('data-url').split('/',4)[3];
            var url_split = dat_url.split('.');
            var url = url_split[0] + '_md.' + url_split[1];

            //var url1_split = url.split('/',4)[3]);

            console.log('Data Url With the split = '+ dat_url);
            console.log('Data Url With the split = '+$(this).attr('data-url').split('.')[1]);
            console.log('Data Url With the split = '+ url);
            console.log('Data Url  = '+ dat_url);

            console.log('Data Url Without the split = '+$(this).attr('data-url'));
            //console.log('Data Url Without the split = '+ url1_split);

            $.ajax({
                type: "GET",
                url: url,
                contentType:'application/x-www-form-urlencoded; charset=UTF-8',
                dataType: "html",
                success: function(response) {
                    console.log(response)
                    p.html(response);
                },
                error: function (xhr, status) {
                  p.html("Error: " + xhr.status + ": " + xhr.statusText);
                }
            });
        }
    );

</script>
{% endblock %}

gallery/templates/gallery/result.html
{% extends "base.html" %}
{% block content %}
{% include 'gallery/search.html' %}
{% include 'gallery/dropdown.html' %}
{% include 'gallery/display_product_search.html' %}
{% endblock %}

gallery/templates/gallery/search.html
 <style>

.sch {
   padding-top:5px;

}

 </style>
 <div class="search">
 <div class="col-sm-6" >
  <form class="navbar-form navbar-left" name="myForm" method='GET' action="{% url 'gallery:search' %}" onsubmit="return validateForm()">
      <div class="form-group">
          <div class = "sch">
        <input type="text" class="form-control" placeholder="Search Product . . ." name="q" value="{{request.GET.q}}">
      <button type="submit" class="btn btn-primary" style = "background-color:#474E5D"><span class="glyphicon glyphicon-search"></span></button>
      </div>
      </div>
    </form>
  </div>
  </div>

  <script>
function validateForm() {
    var x = document.forms["myForm"]["q"].value;
    if (x == "") {
        alert("Fill in product name");
        return false;
    }
}

</script>