cart/urls.py
from django.urls import re_path as url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='details'),   #url to display the cart detail page
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='add'), #definition of url to add items to cart
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='remove'), # the url to remove product from cart

]
    #url(r'^$', views.cart_detail, name='cart_detail'),   #url to display the cart detail page
    #url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'), #definition of url to add items to cart

icanteen/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path as url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^\Z',         include('home.urls')),
    url(r'^admin/',     admin.site.urls),
    url(r'^polls/',     include('polls.urls')),
    url(r'^slideshow/', include('slideshow.urls')),
    url(r'^cart/',      include('cart.urls')),
    url(r'^orders/',    include('orders.urls')),
    url(r'^gallery/',   include('gallery.urls')),
    url(r'^payment/',   include('payments.urls')),
    url(r'^maps/',      include('maps.urls')),
    url(r'^users/',   include('users.urls')),
    url(r'^__debug__/',   include('debug_toolbar.urls')),
  ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import re_path as url
from . import views

app_name = 'payments'

urlpatterns = [
    #url(r'^$',views.index, name='index'),
    url(r'^makepayment/$', views.makepayment, name='makepayment'),
    url(r'^paymentStatus/$', views.paymentStatus, name='status'),
    url(r'^sucess/$', views.success, name='success'),
  ]

payments/models.py
from __future__ import unicode_literals

from django.db import models

class Payment(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    amount = models.CharField(max_length=10)
    tel = models.CharField(max_length=13)
    payment_date = models.DateTimeField(auto_now_add=True)
    processed = models.BooleanField(default=False)

    class Meta: #meta class for ordering orders based on date created
        ordering = ('-payment_date', )

    def __str__(self):
        return 'Payment {}'.format(self.id)




#create your models here

payments/forms.py
from django import forms


class PaymentForm(forms.Form):
    name = forms.CharField(label='Names')

class SubmitForm(forms.Form):
    first_name = forms.CharField(label='First name')
    last_name = forms.CharField(label='Last name')
    cost= forms.DecimalField(max_digits=10, decimal_places=2)
    total_price = forms.IntegerField(localize=True)
    tel = forms.IntegerField(label='Tel',help_text='Number used for payment')
    email = forms.EmailField(label='Email')
    order_date = forms.DateField(label = 'Order Date')
    delivery_date = forms.DateField(label = 'Delivery Date')

payments/views.py
from django.shortcuts import render,redirect
from django.db.models import Q
from orders.models import Order
from payments.models import Payment
from django.core.mail import send_mail
from django.conf import settings
from payments.forms import SubmitForm



#payments view
def makepayment(request):
    if request.method == 'GET':
        query= request.GET.get('q')
        submitbutton= request.GET.get('submit')

        if query is not None:
            print('valid loop')
            form = SubmitForm(request.POST)
            results = Order.objects.filter(Q(first_name__icontains = query) | Q(last_name__icontains = query) & Q(paid=False))
            print(results)
            context={'results': results,
                     'submitbutton':submitbutton,'form':form}
            print(context)
            return render(request, 'payments/makepayment.html', context)
        else:
            return render(request, 'payments/makepayment.html')
    else:
        if request.method == 'POST':
            form = SubmitForm(request.POST)

            if form is not None:
                post=Payment()
                post.first_name= request.POST.get('first_name')
                post.last_name= request.POST.get('last_name')
                post.email= request.POST.get('email')
                post.amount= request.POST.get('total')
                post.tel= request.POST.get('tel')
                post.delivery_date=request.POST.get('datepicker')
                post.save()
                subject = 'New Payment'
                message  = 'A validation request has been sent with the following information.Follow this link to validate it. "http://djangodevelopers.pythonanywhere.com/admin/payments/payment/?processed__exact=0"'+'  '+'Name:'+ post.first_name +' ' + post.last_name +'  '+ 'Email: '+ post.email +'  '+ 'Amount: ' + post.amount +'  ' + 'MoMo Contact: '+ post.tel +'  ' +'Delivery Date: ' + post.delivery_date
                from_email = settings.EMAIL_HOST_USER
                to_list = ['tcourage.tc@gmail.com']
                send_mail(
                           subject,message,from_email,to_list,fail_silently = True,
                           )
                return redirect('/payment/sucess/')
            else:
                form = SubmitForm()
        return render(request, 'payments/makepayment.html')


def payment(request):
    return render (request,'payments/paymentStatus.html',{})
def paymentStatus(request):
    payment_list = Payment.objects.all()
    return render (request,'payments/paymentStatus.html', {'payment':payment_list})

def success(request):
    return render (request,'payments/sucess.html')

# Create your views here.

payments/templates/payments/makepayment.html
<html>
    <head>
     <meta charset="utf-8">
    <title>Icanteen Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=yes">
    <meta name="description" content="The number one Online Canteen Management Project">
    <meta name="Context" content="Object Oriented Software Engineering Course">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>


    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <style>
    h1,p{
      text-align:center;
    }
    .formcontainer {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
  margin: 20px 20px;
}


input[type=submit]{
  border: none;
  color: white;
  padding: 16px 32px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
  border: 1px solid #ccc;
  border-radius: 4px;
}
input[type=text]{
    border: 1px solid #ccc;
    border-radius: 4px;
   padding: 8px 18px;
   margin: 4px 4px;
   width: 50%;
}
</style>

<script>
// call onload or in script segment below form
function attachCheckboxHandlers() {
    // get reference to element containing checkboxes
    var el = document.getElementById('pay');

    // get reference to input elements in  container element
    var checkBoxes = el.getElementsByTagName('input');

    // assign GetSelected function to onclick property of each checkbox
    for (var i=0, len=checkBoxes.length; i<len; i++) {
        if ( checkBoxes[i].type === 'checkbox' ) {
            checkBoxes[i].onclick = GetSelected;
        }
    }
}

function GetSelected() {
        //Reference the form
        var Form = this.form;
        var checkBoxes = Form.getElementsByTagName('input');

        var total = 0;
        var val = parseFloat(Form.elements["total"].value)

        //Loop through the CheckBoxes.

                var row = $(this).closest("tr")[0];
                total = row.cells[2].innerHTML;


                // if check box is checked, add its value to val, otherwise subtract it
                  if (checkBoxes.checked === true ) {
                        val = val + parseFloat(total)
                   } else if(checkBoxes.checked === false )  {
                       val = val - parseFloat(total);
                    }
                // and use it to update value of total text box
                Form.elements['total'].value = val;
}

// format val to n number of decimal places
function formatDecimal(val, n) {
    n = n || 2;
    var str = "" + Math.round ( parseFloat(val) * Math.pow(10, n) );
    while (str.length <= n) {
        str = "0" + str;
    }
    var pt = str.length - n;
    return str.slice(1,pt) + "." + str.slice(pt);
};

function validateForm() {
  var x = document.forms["form"]["q"].value;
  if (x == "") {
    alert("Please a name");
    return false;
  }
};
function validateForm2() {
  var x = document.forms["payform"]["first_name"].value;
  if (x == "") {
    alert("All fields are required");
    return false;
  }
  var name = document.forms["payform"]["last_name"].value;
  if (name == "") {
    alert("All fields are required");
    return false;
  }
  var tel = document.forms["payform"]["tel"].value;
  if (tel == "") {
    alert("All fields are required");
    return false;
  }
  var email = document.forms["payform"]["email"].value;
  if (email == "") {
    alert("All fields are required");
    return false;
  }
  var total = document.forms["payform"]["total"].value;
  if (total == "") {
    alert("All fields are required");
    return false;
  }
  var date = document.forms["payform"]["datepicker"].value;
  var today = new Date();
  var currentDate = today.getDate() ;
  if (date == "" || date < currentDate)  {
    alert("Enter a date ahead of today");
    return false;
  }
};
</script>
    </head>

    {% block content %}
{% include 'payments/navbar.html' %}
<div class="container">
    <div class="row" style="margin-top: 2%">
         <a href="{% url 'payments:status' %}"><button class="btn btn-primary" style=" background-color: #474E5D;">
          Check Status
         </button></a>
    </div>
</div>
          <h1>Send Validation Request Here!</h1>
          <p>You can send validation requests and also check if your order as been processed</p>

<body><div class="formcontainer">
    <p>Please fill this form to search for your order</p>

<form action="{% url 'payments:makepayment' %}" method="GET" value="{{request.GET.q}}" name="form" onsubmit="return validateForm()">
    {% csrf_token %}
<p><input type="text" name="q" value="{{request.GET.q}}" placeholder="Enter Name"  style="border: 1px solid #ccc;border-radius: 4px;padding: 16px 32px;margin: 4px 2px;width: 50%;"></p>
<p><input type="submit" name="submit" value="Search" class="btn btn-primary" style=" background-color: #474E5D;" ></p>
</form>
</div>


<div class="container" style="margin-top:5%" id="pay">

{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
<h3 style="margin-left: 5%">Results for <b>{{ request.GET.q }}</b> = {{results.count}}</h3>

<h1>Select Orders To Pay For</h1>
<form action="." method="POST" value="{{request.POST.q}}" id="paymentForm" name="payform" onsubmit="return validateForm2()">
    {% csrf_token %}

<table align="center" class="table table-striped" id="pay">
    <thead>
      <tr>
        <th><input  type="checkbox" id="select"></th>
        <th>Order ID</th>
        <th>{{form.cost.label_tag}}</th>
        <th>{{form.order_date.label_tag}}</th>
      </tr>
    </thead>
{% for result in results %}
    <tr>
        <td id="select"  class="chckb" ><input  type="checkbox" onchange="GetSelected()"></td>
        <td id="items">{{result.id}}</td>
        <td id="cost">{{result.get_total_cost }}</td>
        <td id="OrderDate">{{result.created}}</td>

   </tr>
   {% endfor %}
  </table>

 <div align="center" class="formcontainer">
     <table style="width:100%" align="center">
         <thead>
             <h2>Personal Information</h2>
         </thead>
    <tr>
  <td align="right">{{form.first_name.label_tag}}</td>
  <td align="left"><input type="text" name="first_name" id="fname"  ></td>
  </tr>
 <tr>
     <td align="right">{{form.last_name.label_tag}}</td>
     <td align="left"><input type="text" name="last_name" id="lname" ></td>
     </tr>
  <tr>
      <td align="right">{{form.email.label_tag}} </td>
      <td align="left"><input type="email" name="email" style="border-radius:4px;padding: 8px 18px;margin: 4px 2px;width: 50%" ></td>
    </tr>
  <tr>
      <td align="right">{{form.total_price.label_tag }}</td>
      <td align="left"><input type="text" value="0" name="total"></td>
   </tr>
  <tr>
      <td align="right">{{form.tel.label_tag }}</td>
      <td align="left"><input type="text" name="tel" placeholder="Number used for MoMo/OrngeMoney Payment" id="tel" ></td>
    </tr>
  <tr>
      <td align="right">{{form.delivery_date.label_tag }}</td>
      <td align="left"><input type="date" name="datepicker" style="border-radius:4px;padding: 8px 18px;margin: 4px 2px;width: 50%" ></td>
    </tr>

  </table>
  </div>

<p style="margin-top:2%"><input type="submit" name="save" value="Send" class="btn btn-primary" style=" background-color: #474E5D;" id="save"></p>
{% else %}
Sorry!!!!No results for <b>{{ request.GET.q }}</b>. Try another name(A first or last name)
{% endif %}
{% endif %}
</form>
<script>attachCheckboxHandlers();</script>
{% endblock content %}
</div>
</body>
{% include 'gallery/footer.html' %}
</html>

payments/templates/payments/navbar.html
<style>
    .navbar {
            padding-top: 15px;
            padding-bottom: 15px;
            border: 0;
            border-radius: 0;
            margin-bottom: 0;
            font-size: 12px;
            letter-spacing: 5px;
        }
        .navbar-nav li a:hover {
            color: #1abc9c !important;
        }

</style>

   <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">Us</a>
            </div>
            <div class=" collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'gallery:product_list' %}">Gallery</a></li>
                    <li><a href="#">Cart</a></li>
                    <li><a href="#">Polls</a></li>
                </ul>
            </div>
        </div>
    </nav>

payments/templates/payments/paymentStatus.html
<html>
    <head>
     <meta charset="utf-8">
    <title>Icanteen Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=yes">
    <meta name="description" content="The number one Online Canteen Management Project">
    <meta name="Context" content="Object Oriented Software Engineering Course">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"> </script>
    <script src="https://cdn.datatables.net/select/1.3.0/js/dataTables.select.min.js"></script>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link href="https://cdn.datatables.net/select/1.3.0/css/select.dataTables.min.css">


<style>
.container1 {
    border-radius: 5px;
    padding: 20px;
  margin: 20px 20px;
}
</style>
<script>
    $(document).ready(function() {
    $('#status').DataTable( {
        columnDefs: [ {
            orderable: true,
            targets:   1
        } ],
        select: {
            style:    'os',
            selector: 'td:first-child'
        },
        order: [[ 1, 'asc' ]]
    } );
} );

</script>
    </head>

<body>
{% block content %}
{% include 'payments/navbar.html' %}
<h1 align="center">Validated Payments</h1>
<div class="container">
    <div class="row" style="margin-top: 2%">
         <a href="{% url 'makepayment' %}"><button class="btn btn-primary" style="background-color: #474E5D;">
          Make Request
         </button></a>
    </div>
</div>
<div style="float:right ">
    <input type="button" class="btn btn-primary" style="background-color: #474E5D;" id="bt" onclick="print()" value="Print PDF" />
</div>
<div class="container1 " style="margin-top:5%" id="content">
<table align="center" class="table table-striped" id="status">
    <thead>
        <tr>
            <th>Date Of Request</th>
            <th>Customer</th>
            <th>Amount Paid</th>
            <th>Status</th>
        </tr>
    </thead>
{% for payment in payment %}
    <tr>
        <td>{{payment.payment_date}}</td>
        <td>{{payment.first_name}}  {{payment.last_name}}</td>
        <td>{{payment.amount}}FCFA</td>
        <td>{% if payment.processed %}Validated{% else %}Pending validation{% endif %}</td>
    </tr>
   {% endfor %}
</table>
</div>
{% include 'gallery/footer.html' %}
{% endblock content %}
</body>
</html>

payments/templates/payments/sucess.html
<html>
    <head>
     <meta charset="utf-8">
    <title>Icanteen Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=yes">
    <meta name="description" content="The number one Online Canteen Management Project">
    <meta name="Context" content="Object Oriented Software Engineering Course">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <style>
    h1{
        padding: 20px;
        margin-top: 10%;
        margin-bottom: 10%;
    }
    .mcontainer{
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
        margin: 20px 20px
    }

    </style>
     </head>

<body>
<div class="mcontainer">
  <h1 class="display-3" align ="center">Thank You!</h1>
  <p id="text" class="lead" align = "center"><strong>Your payment will be processed shortly!!!</strong> </p>
  <hr>
  <div class="container" align="center">
    <div class="row" style="margin-top: 2%">
         <a href="{% url 'makepayment' %}"><button class="btn btn-primary" style=" background-color: #474E5D;">
          Go Home
         </button></a>
    </div>
</div>
</div>
</body>
{% include 'gallery/footer.html' %}
</html>